CREATE TABLE vef_v2(
   DATE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
   NAME           VARCHAR(100)  NOT NULL,
   EMAIL          VARCHAR(100)  NOT NULL,
   SSN            VARCHAR(50)   NOT NULL PRIMARY KEY,
   COUNT          INT           NOT NULL 
);